---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-servicemonitor
  namespace: monitoring
  labels:
    app: api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
    - video-processing
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-servicemonitor
  namespace: monitoring
  labels:
    app: worker
    release: prometheus
spec:
  selector:
    matchLabels:
      app: worker
  namespaceSelector:
    matchNames:
    - video-processing
  endpoints:
  - port: metrics
    path: /metrics
    interval: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-servicemonitor
  namespace: monitoring
  labels:
    app: rabbitmq
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rabbitmq
  namespaceSelector:
    matchNames:
    - video-processing
  endpoints:
  - port: management
    path: /metrics
    interval: 5s
